### ISSUE TITLE
Get error, please help

### ISSUE THREAD

**Issue by jt387** [endgameinc/dga_predict#3]
I run the dga_predict on windows,   the environment is below:
(tensorflow) C:\JT\deeplearning\dga\dga_predict-master>pip freeze
backports.weakref==1.0rc1
bleach==1.5.0
certifi==2018.1.18
chardet==3.0.4
cycler==0.10.0
h5py==2.7.0
html5lib==0.9999999
idna==2.6
Keras==2.1.3
Markdown==2.6.11
matplotlib==2.0.2
numpy==1.14.0
protobuf==3.5.1
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
requests==2.18.4
requests-file==1.4.3
scikit-learn==0.19.1
scipy==0.19.1
six==1.11.0
sklearn==0.0       (I notice here  looks stange! )
tensorflow==1.2.1
tldextract==2.2.0
urllib3==1.22
Werkzeug==0.14.1
wincertstore==0.2

And the error information is below:
(tensorflow) C:\JT\deeplearning\dga\dga_predict-master>python run.py
Using TensorFlow backend.
C:\Users\Admin\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\cross_validat
ion.py:41: DeprecationWarning: This module was deprecated in version 0.18 in fav
or of the model_selection module into which all the refactored classes and funct
ions are moved. Also note that the interface of the new CV iterators are differe
nt from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "run.py", line 95, in <module>
    create_figs(nfolds=1) # Run with 1 to make it fast
  File "run.py", line 34, in create_figs
    bigram_results, lstm_results = run_experiments(isbigram, islstm, nfolds)
  File "run.py", line 23, in run_experiments
    bigram_results = bigram.run(nfolds=nfolds)
  File "C:\JT\deeplearning\dga\dga_predict-master\dga_classifier\bigram.py", lin
e 23, in run
    indata = data.get_data()
  File "C:\JT\deeplearning\dga\dga_predict-master\dga_classifier\data.py", line
130, in get_data
    gen_data(force)
  File "C:\JT\deeplearning\dga\dga_predict-master\dga_classifier\data.py", line
120, in gen_data
    domains, labels = gen_malicious(10000)
  File "C:\JT\deeplearning\dga\dga_predict-master\dga_classifier\data.py", line
48, in gen_malicious
    domains += banjori.generate_domains(segs_size, banjori_seed)
  File "C:\JT\deeplearning\dga\dga_predict-master\dga_classifier\dga_generators\
banjori.py", line 16, in generate_domains
    for i in range(nr_domains):
TypeError: 'float' object cannot be interpreted as an integer

The python version is 3.5.4,  and i used 2to3 to change the code.   Any response will be appreciated,  thanks!

**Comment by jt387** [comment]
I run the codes sucessfully,  it should modify some codes to run in the python3.x version.

**Comment by KuangHao95** [comment]
Just change "/" to "//" (mostly inside dga_generators folder). 
For in Python 2, inputs for range() function are used as int, while Python 3 does not. So you need to make sure every input to range() is int by hand.
